replicaCount: 1

image:
  repository: timescale/timescaledb
  tag: latest-pg12
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 8Gi

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

postgresUser: postgres
postgresPassword: postgres
postgresDatabase: main

nodeSelector: {}
tolerations: []
affinity: {}
